### ISSUE TITLE
Transaction acceptance vs. Block ratified acceptance

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iota-core#123]
The current way transaction are included in a slot is incompatible with the way blocks (and attachments) are included in a slot.
Blocks are included when they are ratified acceptance.
A TX is included if its attachment is included and its conflict is accepted.
This approach is incompatible.

Possible solutions:
1. Count TX votes only coming from ratified accepted blocks.
2. Model ratified acceptance on top of acceptance also on UTXO DAG and ConflictDAG.

Addressed as part of #116

**Comment by jonastheis** [comment]
Closed with #127
