### ISSUE TITLE
Private Network - Question

### ISSUE THREAD

**Issue by damianlluch** [iotaledger/iota-core#135]
Good morning, apologies if this is not the right place to leave a question, we are planning with a colleague to use IOTA for a project with iOT, but the idea is that it is in a private blockchain (or private tangle) disconnected from the iota network. This is possible in this project? similar to Hyperledger Besu.

thanks

**Comment by alexsporn** [comment]
Hi, this node software is still in development and not ready to be run. Please have a look at the wiki on how to run a private tangle with HORNET (the current node implementation). See https://wiki.iota.org/shimmer/hornet/how_tos/private_tangle/
