### ISSUE TITLE
Delegation & staking spammer

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iota-core#222]

**Comment by karimodm** [comment]
There is some overlap between inx-spammer and evil tooling around accounts: sync up and decide on a common approach with differentiating factors.

**Comment by karimodm** [comment]
End-to-end accounts test have higher priority for now #466

**Comment by muXxer** [comment]
Related to 
https://github.com/iotaledger/evil-tools/issues/38 and https://github.com/iotaledger/evil-tools/issues/37

**Comment by muXxer** [comment]
This is a duplicate and can be closed.
