### ISSUE TITLE
Resolve conflicts related TODOs

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/iota-core#256]
* [x] Revisit logic in `inheritConflicts` for shallowLikeParent.
        file: `pkg/protocol/engine/booker/inmemorybooker/booker.go`

* [x] Evaluate deadlock of `likedInsteadMutex` and `structureMutex`
        file: `pkg/protocol/engine/mempool/conflictdag/conflictdagv1/conflict.go`

* [x] In `UnacceptedConflicts`, Introduce optsMergeToMaster
        file: `pkg/protocol/engine/mempool/conflictdag/conflictdagv1/conflictdag.go`

* [x] In `NewSortedConflicts`, use workerpool instead of goroutines
       file: `pkg/protocol/engine/mempool/conflictdag/conflictdagv1/sorted_conflicts.go`

* [x] In booker add TransactionInvalid event.

**Comment by piotrm50** [comment]
> In UnacceptedConflicts, Introduce optsMergeToMaster

Don't need this, removed the TODO.

**Comment by piotrm50** [comment]
> Evaluate deadlock of likedInsteadMutex and structureMutex.

Impossible to deadlock if all transactions are forked. Removed the TODO but left the description.

**Comment by piotrm50** [comment]
> In NewSortedConflicts, use workerpool instead of goroutines.

Decided to leave it as it is for now as the whole conflictDAG will eventually be rewritten using the reactive framework, so it doesn't make sense to change it now, given that it works.
