### ISSUE TITLE
Resolve ledger & mempool TODOs

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/iota-core#257]
* [x] In `e.HookConstructed`,
	* [x] Create an Init method that is called with all additional dependencies on e.HookInitialized()
	* [x] How to handle changing API?
	* [x] Decide when to prune the spent ledger state. (Currently evicts as soon as `SlotFinalized` triggered) -> should be addressed by https://github.com/iotaledger/iota-core/pull/288
* [x] In `processCreatedAndConsumedAccountOutputs`, do we even need to check for staking feature here if we require BlockIssuer with staking?
* [x] Create a test case that checks to transition a delegation output twice in the same slot.
* [x] In `blockPreAccepted`, need to check what kind of error and potentially mark the block as invalid if failed to cast a vote for block.

file: `pkg/protocol/engine/ledger/ledger/ledger.go`

---
* [x] In `executeStardustVM`
	* [x] Refactor resolution of ContextInputs to be handled by Mempool
	* [x] Double-check the slot index of the transaction to retrieve API. (Currently it is CreationTime)

file: `pkg/protocol/engine/ledger/ledger/vm.go`

---
* [x] In `AddTransaction`, use error handler for logging in `Transaction.OnPending`.

file: `pkg/protocol/engine/mempool/v1/state_diff.go`

**Comment by piotrm50** [comment]
> In blockPreAccepted, need to check what kind of error and potentially mark the block as invalid if failed to cast a vote for block.
// TODO: here we need to check what kind of error and potentially mark the block as invalid.
//  Do we track witness weight of invalid blocks?


Subjectively invalid blocks do add witness weight, but do not add approval weight. 
The only conflict that can occur is that the same conflict is both supported and revoked, which means that the block is 
"subjectively invalid" and it shouldn't be marked as objectively invalid along with its whole future cone.

**Comment by piotrm50** [comment]
> do we even need to check for staking feature here if we require BlockIssuer with staking?

Doesn't hurt to check - removed TODO.

**Comment by piotrm50** [comment]
> Create an Init method that is called with all additional dependencies on e.HookInitialized()

Seems to be outdated as I can't figure out what it's about. Removed TODO.

**Comment by piotrm50** [comment]
> Create a test case that checks to transition a delegation output twice in the same slot.

Part of the hardening phase, not necessary to resolve that now. I extended the test a little bit, but  it needs to be fully covered later during hardening. Marking as "done" for now and removing the TODO.

**Comment by piotrm50** [comment]
> Double-check the slot index of the transaction to retrieve API. (Currently it is CreationTime)

Transaction's CreationTime makes the most sense as it's the only always-available objective time in a transaction.
