### ISSUE TITLE
Resolve performance TODOs

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/iota-core#258]
* [x] In `BlockAccepted`, 
	* [x] check if the block is validation block
	* [ ] ~include wannabe validator performance in the snapshot~
* [ ] ~Finish `EligibleValidatorCandidates`~
* [x] In `aggregatePerformanceFactors`, scale the result by the number of slots per epoch

file: `pkg/protocol/sybilprotection/sybilprotectionv1/performance/performance.go`

---
* [x]  Move parameters to protocol params.
* [x]  Decide default value for parameters.
* [x]  In `ValidatorReward` and `DelegatorReward`, double check reward calculation: the epoch should be returned by the reward calculations and we should only loop until the current epoch, not epochEnd.
* [x]  In `poolReward`, deal with the potential overflow issue

file: `pkg/protocol/sybilprotection/sybilprotectionv1/performance/rewards.go`

---
* [x]  In `importPerformanceFactor`, 
	* [x] discuss: lower number of accounts to `uint8`
	* [x] discuss: the upper bound of performance factor, maybe `uint16` is enough
* [x]  In `exportPoolRewards`, adjust the loop to calculate rewards

file: `pkg/protocol/sybilprotection/sybilprotectionv1/performance/snapshot.go`

**Comment by daria305** [comment]
We postpone implementation of registration and candidates activity tracking, so some tasks were crossed out.
