### ISSUE TITLE
Add only strong parent to RootBlock

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/iota-core#260]
* [ ] Add only strong parent to RootBlock (Currently iterate through all parents)
* [ ] Evaluate if adding RootBlock in BlockAccepted will lock acceptance 

file: `pkg/protocol/engine/engine.go`

**Comment by piotrm50** [comment]
> Add only strong parent to RootBlock (Currently iterate through all parents) 

I think as long as we solidify and propagate weight through all parent types, root blocks should contain all types of parents as it is implemented now.
