### ISSUE TITLE
Pass protocol params from the config to protocol upgrade orchestrator

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/iota-core#265]
file: `components/protocol/component.go`

**Comment by jonastheis** [comment]
This is necessary as can be seen on the following flow of events: 

Example for non-validator node:
1. Start node and import protocol parameters for version 3 from snapshot
2. nothing to import from config
3. Upgrade gets voted upon and accepted -> needs to update node version soon
4. Whenever we commit and `VersionsAndProtocolParametersHash` is called, the parameters can't be found in `protocolParametersByVersion` -> have to be in `futureProtocolParametersByVersion`
4. Shuts down node, starts with new software and parameters in config
5. Import parameters via `StoreProtocolParameters`
	- adds to storage: `version:protocolparameters`
	- delete future parameters
	- calls: `apiProvider.AddProtocolParameters`
		- removes from future map
		- adds to `protocolParametersByVersion` map
		- potentially increases latest version
6. Whenever apiProvider APIForSlot/Epoch is called, the correct version based on the starting epoch is returned. ie the new version is only returned if the epoch is bigger equal than the activation epoch of the upgrade
7. Whenever we commit and `VersionsAndProtocolParametersHash` is called, the parameters can be found in `protocolParametersByVersion` and we compute the hash thereof
