### ISSUE TITLE
Resolve sybil protection TODOs

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/iota-core#267]
* [x] In `e.HookInitialized`, how to handle changing API?
* [x] See if the check in `ElegibleValidators` is still needed
* [x] `weightedCommittee` returned by the PoA sybil protection does not have stake specified, which will cause problems during rewards calculation.
* [x] add latest supported protocol version to account data so that it can be used in `OrderedRegisteredCandidateValidatorsList`

file: `pkg/protocol/sybilprotection/sybilprotectionv1/sybilprotection.go`

**Comment by piotrm50** [comment]
>  See if the check in ElegibleValidators is still needed
No change needed as we will re-evaluate this when implementing candidate registration.

**Comment by piotrm50** [comment]
> In e.HookInitialized, how to handle changing API?

I don't think we need to worry about changing API here, as we're only interested in current epoch which is calculated using `CurrentAPI` (according to the last committed slot), and the next epoch is always calculated as `currentEpoch+1` - but we don't need API for that slot for anything. 

Removing the TODO.

**Comment by piotrm50** [comment]
> returned by the PoA sybil protection does not have stake specified, which will cause problems during rewards calculation.

This one was resolved some time ago but TODO wasn't removed.
