### ISSUE TITLE
evil spammer allotting Mana in tx and burning Mana in blocks according to RMC

### ISSUE THREAD

**Issue by cyberphysic4l** [iotaledger/iota-core#285]
The evil spammer needs to allot Mana in its transactions to the issuer account that creates its blocks. The blocks also need to burn the correct amount of Mana according to RMC and the WorkScore of the block.

**Comment by cyberphysic4l** [comment]
It would be nice to have a function that precalculates the workScore of the block before even creating the transaction, so that the transaction can allot the correct amount.

**Comment by daria305** [comment]
Precalculation feature done in #345

**Comment by daria305** [comment]
left TODO:
 - As the node will not have BlockIssuer component we need to make EvilSpammer create the blocks. With this there is no need take of alloting mana to node. 
 - we will use this workscore calculation from #345
 - the evil wallet should have account setup with private keys to sign and prepare blocks (issue #206)
