### ISSUE TITLE
Implement enhanced performance factor

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/iota-core#308]
In the context of #240 the discussion came up whether we actually need or should implement a special tip selection for validators because a special tip selection for validators might make regular block issuers adjust their optimal tip selection strategy accordingly. Therefore, we won't implement a special tip selection mechanism but instead **provide the right incentives for validators via adjusting their performance factor (and thus rewards)** to do their job efficiently. 

There are a few aspects that cover this topic:
1. a validator is supposed to issue a block in a regular interval: performance factor will be decreased if not
2. each validation block needs to reference own previous block directly: if not done correctly, rewards will be 0
3. maximize the number of regular blocks between past cone of current and previous validation block: this should be normalized and applied to the performance factor

This way the optimal strategy for validators is to pick up as many tips as possible in a URTS fashion while it does not influence the optimal strategy for regular block issuers (still URTS).

## 1. a validator is supposed to issue a block in a regular interval

- To speed up confirmation times, issuing of blocks should be staggered. The question here is how? Should there be a deterministic time a validator/seat should issue a block? Or is it sufficient to say that a validator should issue a block in each subslot (eg slot / 10 if should issue 1 validation block per second). 
- How does violation of this impact the performance factor?
  - too many blocks (malicious behavior)
  - too few blocks (offline, not doing job properly)

#### **Attack**: issue multiple validation blocks at the same time and send one to each validator
- At max malicious node can sneak committeeSize validation blocks per subslot
- Do we need to stop scheduling such blocks?  Be careful with this as it might lead to the orphanage of other validation blocks who accidently reference non-scheduled blocks. So, at which moment  - for instance, wait when others understand who is an equivocator - when the slot is committable?
- The validator’s reward for the entire epoch will be slashed

## 2. each validation block needs to reference own previous block directly

- Do we need to introduce a special reference for this in the validation block?
- What happens if a validator was offline/switched chain and can't reference its previous block?
- What happens if previous block got orphaned?
  - Seems reasonable to have an assumption that all your own validation blocks are accepted in your perception. Then switch the chain once you realize that another chain is heavier. To help minimizing this it might be an option to create a separate tip pool for not yet referenced validation blocks and reference them **directly**.
 
## 3. maximize the number of regular blocks between past cone of current and previous validation block
- How exactly is the "counting" of past cones done efficiently and without being attackable by a malicious committee member?
- How and acccording to what (slot/subslot) do we normalize? 
- How does this factor influence the overall performance of a slot?

#### **Attack**: What do we do when validator issues very infrequent blocks?
- We only walk x subslots (interval in which the validator should have issued) as this should already cover all blocks that can be referenced if validator would’ve issued regular blocks. -> Think about 2 subslots as a network delay assumption. 
- Need to be careful about this as this might lead to orphanage: needs to walk further as otherwise validators would not pick up blocks with timestamp below this subslot boundary

**Comment by karimodm** [comment]
Determining the quality of the past cone could be feasible through past-cone walk or heaviest-branch bitmask; both option have been discussed at length.
We decided to track validators' performance exclusively on the frequency of their issuing: the effort of implementing such tracking does not justify the risks.
