### ISSUE TITLE
Problems while trying to compile iota IRI Java

### ISSUE THREAD

**Issue by lcdsl88** [iotaledger/iota-core#340]
Hi everyone! I am a PhD student from Brazil trying to compile IOTA IRI in Java for Academic purpose. I'm currently over an issue while trying to compile de pom file in Java following the steps of https://github.com/iotaledger/iri. The log of the error is as follows:

[INFO]

[INFO] ----------------------------< com.iota:iri >----------------------------

[INFO] Building IRI 1.8.6

[INFO] from pom.xml

[INFO] --------------------------------[ jar ]---------------------------------

Downloading from jitpack.io: [https://jitpack.io/com/github/…APSHOT/maven-metadata.xml](https://jitpack.io/com/github/iotaledger/java-md-doclet/master-SNAPSHOT/maven-metadata.xml)

[WARNING] Could not transfer metadata com.github.iotaledger:java-md-doclet:master-SNAPSHOT/maven-metadata.xml from/to jitpack.io (https://jitpack.io/): status code: 401, reason phrase: Unauthorized (401)

[WARNING] com.github.iotaledger:java-md-doclet:master-SNAPSHOT/maven-metadata.xml failed to transfer from https://jitpack.io/ during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced. Original error: Could not transfer metadata com.github.iotaledger:java-md-doclet:master-SNAPSHOT/maven-metadata.xml from/to jitpack.io (https://jitpack.io/): status code: 401, reason phrase: Unauthorized (401)

Downloading from jitpack.io: [https://jitpack.io/com/github/…oclet-master-SNAPSHOT.pom](https://jitpack.io/com/github/iotaledger/java-md-doclet/master-SNAPSHOT/java-md-doclet-master-SNAPSHOT.pom)

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 1.054 s

[INFO] Finished at: 2023-09-10T14:32:06-03:00

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal on project iri: Could not resolve dependencies for project com.iota:iri:jar:1.8.6: Failed to collect dependencies at com.github.iotaledger:java-md-doclet:jar:master-SNAPSHOT: Failed to read artifact descriptor for com.github.iotaledger:java-md-doclet:jar:master-SNAPSHOT: The following artifacts could not be resolved: com.github.iotaledger:java-md-doclet:pom:master-SNAPSHOT (absent): Could not transfer artifact com.github.iotaledger:java-md-doclet:pom:master-SNAPSHOT from/to jitpack.io (https://jitpack.io/): status code: 401, reason phrase: Unauthorized (401)

Reading forums people facing similar issues, it seams that the repository is private.

Does anyone have the same issue and get any idea how can I fix it and compile the Java IRI file?

The solution to this issue it will be crucial for me to continue my research

Sorry publishing this issue on iota-core but the IRI repository has been archived

**Comment by Dr-Electron** [comment]
This is not the IRI repo, but the repo for the future IOTA Node software. IRI was deprecated a long time ago

**Comment by lcdsl88** [comment]
> This is not the IRI repo, but the repo for the future IOTA Node software. IRI was deprecated a long time ago

I could actually compile the Java files of the repository https://github.com/iotaledger/iota-java but when I try to run the JAR file the following ERROR is presented and IOTA client doesn't start:

no main manifest attribute, in jota-1.0.0-beta9-jar-with-dependencies.jar

Does anyone can help me?

**Comment by jlvandenhout** [comment]
@lcdsl88 The repos you refer to are both for the legacy IOTA network and both deprecated. Please read [the Wiki](https://wiki.iota.org/), you will find descriptions of the current networks we provide and their associated node implementations and libraries.

**Comment by lcdsl88** [comment]
Thank you for the reply. 

Anyone who does have an idea or the solution for this issue feel free to email me at lcsl@protonmail.ch

I would apreciate!

**Comment by jonastheis** [comment]
As was pointed out, this is unrelated to iota-core. Therefore, closing this issue.
