### ISSUE TITLE
Problem when trying to run IOTA java compiled file

### ISSUE THREAD

**Issue by lcdsl88** [iotaledger/iota-core#341]
Good afternoon! I hope you're doing fine!

I am a brazilin PhD student researching IoT blockchains. 

I'm trying to compile IOTA in Java and running a node locally and performe the API commands. 

I could actually compile the Java files of the repository https://github.com/iotaledger/iota-java and the Jar file is created (jota-1.0.0-beta9-jar-with-dependencies). 

But when I try to run the JAR file with java -jar command the following ERROR is presented and IOTA client doesn't start:

**no main manifest attribute, in jota-1.0.0-beta9-jar-with-dependencies.jar**

Does anyone can help me?

It will be crucial to my research compiling IOTA in Java and sucessfully running a node and the API commands.

Sorry about posting this issue at iota-core forum but the iota-java repository has been archived

**Comment by jonastheis** [comment]
As was pointed out in #340 , this is unrelated to iota-core. Therefore, closing this issue.
