### ISSUE TITLE
Migrate stardust's users to accounts on IOTA 2.0

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iota-core#350]
Migrate aliases w/ the serialized block issuer feature in the Metadata Feature to accounts w/ block issuer features on 2.0 upgrade.

**Comment by william-fabian-sanders** [comment]
This has mostly been covered by the use-ability taskforce. The conclusion is that we will have two methods for upgrade.  

1. Prelaunch upgrade: Before the launch of IOTA Core v1.0 on shimmer, people who know what they are doing can (A) use the IOTA 2.0 SDK to create a block issuer feature, (B) serialize it, and (C) use IOTA 1.5 SDK to publish this feature on the ledger in the meta-data associated to an alias output.  When we do the upgrade to  IOTA Core v1.0, the accounts generated from these alias outputs will have the block issuer feature enabled (assuming the alias has the funds to pay the extra deposit)

2. Post upgrade: We will enable people to use a service provider to issue blocks for the user where the user reimbuses the service provider for the mana.  This service provider will not make a profit, and will mostly likely only be the IF.  We will run this service for about a year, as we wait for a more sophisticated solution that will be built with the community.
