### ISSUE TITLE
Deprecate old payload types

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/iota-core#353]
We have `PayloadTreasuryTransaction` and `PayloadMilestone` in the payload types, both of which should be deprecated.

https://github.com/iotaledger/iota.go/blob/0195b309ac09bb1eaf9563907eefbdfb67794b45/payload.go#L24

**Comment by alexsporn** [comment]
We should also verify the AccountOutput is really just a rename from the AliasOutput. If the layout changed we should rather deprecate the Alias and give Accounts a new type number.

**Comment by alexsporn** [comment]
Maybe we can reset all types since we won't support old structures anyway. This requires an explanation in the TIPs

**Comment by muXxer** [comment]
done in https://github.com/iotaledger/iota.go/pull/558
