### ISSUE TITLE
Test_StartNodeFromSnapshotAndDisk hangs on -race tests

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iota-core#446]
[logs.txt.zip](https://github.com/iotaledger/iota-core/files/13042680/logs.txt.zip)

**Comment by karimodm** [comment]
Too dependant on #496 and #320 PRs.

**Comment by jonastheis** [comment]
I've been running this test with `-race` for more than 30min on latest develop [b13c7de](https://github.com/iotaledger/iota-core/commit/b13c7dee4082c02f44268abf4d614c7ab564cee8) and could not observe it hanging anymore. Closing issue for now.
