### ISSUE TITLE
Add constraints to the parameters

### ISSUE THREAD

**Issue by oliviasaa** [iotaledger/iota-core#450]
Some parameters are not completely independent and others can't use more than a certain number of bits. I'll collect the constraints below so we can add a check at some point:
1) `p.decayFactorEpochsSum*p.generationRate` must use less than 32 bits
2) generationRate and generationExp must be consistent with the total supply (among other parameters) to prevent overflowing

**Comment by jonastheis** [comment]
Addressed with https://github.com/iotaledger/iota.go/pull/606
