### ISSUE TITLE
Check if transaction metadata endpoint makes sense

### ISSUE THREAD

**Issue by muXxer** [iotaledger/iota-core#456]
IMO users sometimes don't care about the blocks which contain a transaction, but only about the transaction itself.
If it's possible, we should add a tx metadata endpoint.

**Comment by karimodm** [comment]
Let's agree on having an endpoint to obtain Transaction's metadata, as we report and retrieve rejection reason and such over TXs instead of Blocks.

**Comment by karimodm** [comment]
Endpoint still needs to be added.

**Comment by muXxer** [comment]
@jkrvivian we need to discuss if it should be connected to the blockId in the retainer, or stored separately.
