### ISSUE TITLE
Time precision

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/iota-core#498]
Currently, the time in a `BlockHeader` is represented using the Go type [`time.Time`](https://github.com/iotaledger/iota.go/blob/develop/block.go#L61). This works fine as we serialize this to a `uint64` using [`TimeToUint64`](https://github.com/iotaledger/hive.go/blob/develop/serializer/serializer.go#L474) with nanosecond precision. 

The question is: **do we really need nanosecond precision?**

Arguably, nanosecond scale is rather useless and just makes it harder to parse/read. 
But on the other hand, decreasing precision to let's say seconds is not fine enough, as we have the rule of timestamp monotonicity on blocks.

If we decide for some precision in between, it might make sense to implement our own type for time with it's own serialization as well.

**Comment by cyberphysic4l** [comment]
I would say that millisecond precision would also not be enough: if we have 1000 BPS, then we would already not have unique timestamps most of the time. 

So it's between microseconds and nanoseconds. And then the question is, how much are we saving by reducing precision by a factor of 1000? Wouldn't we still need to use a uint64?

**Comment by karimodm** [comment]
Let's take a decision here: block's time granularity should be in **nanoseconds** while protocol parameters should either be in **seconds** or **slots** whenever applicable.
