### ISSUE TITLE
Sanity checks for protocol parameters & derive parameters as much as possible

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/iota-core#512]
It would be great to have sanity checks for protocol parameters in place that evaluate whether a certain combination of parameters makes sense. This could, for example happen, when constructing the protocol parameters and the function that does all these checks could serve as a documentation going forward as to which parameters are related and how. 

The functionality should have different levels of escalation:
- for sensible parameters for a live network: this should warn, so that it's still possible to overwrite them e.g. in unit or end-to-end tests
- impossible combinations of parameters: this should panic

**Comment by cyberphysic4l** [comment]
The parameters taskforce has prepared a dependency graph for protocol parameters which can be found here. This should be our start point for these sanity checks.
https://hackmd.io/EsdW9f4fRKucYAaUFDfS_g?view#Dependency-Graph-Represented-by-Inequality
