### ISSUE TITLE
Make activity window a protocol parameter

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/iota-core#519]
The `ActivityTracker` was recently changed to work based on protocol time (solid blocks seen, and filtered) instead of real time.

```go
e.Events.CommitmentFilter.BlockAllowed.Hook(func(block *blocks.Block) {
	// Only track identities that are part of the committee.
	committee, exists := s.CommitteeInSlot(block.ID().Slot())
	if !exists {
		panic(ierrors.Errorf("committee not selected for slot %d, but received block in that slot", block.ID().Slot()))
	}

	seat, exists := committee.GetSeat(block.ProtocolBlock().Header.IssuerID)
	if exists {
		s.activityTracker.MarkSeatActive(seat, block.ProtocolBlock().Header.IssuerID, block.IssuingTime())
	}

	s.events.BlockProcessed.Trigger(block)
})
```

Therefore, having it as a local node configuration does not make much sense as different activity windows would lead to a different perception of online committee, thus leading to different commitments. Instead, it should be part of the protocol parameters.

**Comment by piotrm50** [comment]
During the discussions so far we've concluded that ActivityWindow cannot be bigger than MaxCommittableAge as this leads to ValidatorNodes creating ForcedCommits, which is undesired if there are still some online validators.

**Comment by cyberphysic4l** [comment]
> During the discussions so far we've concluded that ActivityWindow cannot be bigger than MaxCommittableAge as this leads to ValidatorNodes creating ForcedCommits, which is undesired if there are still some online validators.

Would it make sense to simply use MaxCommittableAge as our activity window? Then we don't need a parameter, that is simply our activity window.
