### ISSUE TITLE
Use actual network id in blocks

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota-core#544]
Currently the blocks all have `"networkId":"0"` which is wrong, it should be set to the first 8 bytes of the BLAKE2b-256 hash of the concatenation of the network type and the protocol version string. https://github.com/iotaledger/tips/blob/tip46/tips/TIP-0046/tip-0046.md#block

**Comment by PhilippGackstatter** [comment]
This should no longer be an issue since iotaledger/iota.go#627 was merged. IOTA-Core was updated since then to use that iota.go version, so when constructing blocks with the builder it should now use the network ID from the protocol parameters by default. Can you confirm that this is fixed?

**Comment by Thoralf-M** [comment]
Yes fixed now, thanks
