### ISSUE TITLE
Reassess the use of LatestCommitment from Settings or SyncManager over all components

### ISSUE THREAD

**Issue by muXxer** [iotaledger/iota-core#561]
Do we use the correct one of both in every place? I saw that we use the Settings one in the "inx server" code, which is wrong IMO.
We agreed to check all occurrences in the code again.

**Comment by karimodm** [comment]
Perhaps introduce a reactive variable as the only single point of truth to receive latest commitment updates and state.

**Comment by alexsporn** [comment]
Most API and INX components use the SyncManager because it provides multiple values in a consistent (mutex-locked) way. Maybe it might be a good idea to connect the SyncManager values to the Settings in a reactive way.
