### ISSUE TITLE
Solid blocks are re-requested and not found in block cache

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/iota-core#565]
In `TestLossOfAcceptanceFromGenesis` the following occurred:

![Image](https://github.com/iotaledger/iota-core/assets/4181434/41aff5bb-9ec9-4800-a3e2-e0dedc688408)

It seems that blocks get solid and then are not found in the block cache anymore.

When looking at the entire [log.txt](https://github.com/iotaledger/iota-core/files/13474445/log.txt) of the test, it seems that the node was warpsycing and solidifying the tangle from the tip at the same time. Which might lead to resetting the engine within the warpsync process. Thus, leading to some weird errors at any point in the data flow. 

This might be addressed with #293 as there's different modes for warpsync and normal mode operation.

**Comment by piotrm50** [comment]
Maybe it's affected by the fix in #566

**Comment by jonastheis** [comment]
Should be fixed with #293
