### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by shufps** [iotaledger/iota-core#634]
We have the problem that memory fills up slowly but steady:

![image](https://github.com/iotaledger/iota-core/assets/3079832/5c377186-f20e-4347-a3ee-a11b63a91f88)

Here is a pprof profile from one node:

[iota-core.zip](https://github.com/iotaledger/iota-core/files/13691689/iota-core.zip)

A perhaps helpful additional information is that after a restart it consumes about the same amount of memory after about 1-2 minutes, so it doesn't seem to be a leak but really be used by something.

Unfortunately the only option we have right now to workaround this is to completly wipe the nodes and start with a fresh network.

edit:
after restarting it consumes even more:
![image](https://github.com/iotaledger/iota-core/assets/3079832/040faf32-f8e9-43cc-b269-2c43719662d6)

and golang heap:
![image](https://github.com/iotaledger/iota-core/assets/3079832/a0b35456-4dbe-4b3e-b005-8dccf1277944)

A second profile after restarting:
[iota-core.zip](https://github.com/iotaledger/iota-core/files/13691720/iota-core.zip)

**Comment by alexsporn** [comment]
@shufps do you have any updates after changing the configuration?

**Comment by shufps** [comment]
At `alpha.4` we still have memory leaks, like:
![image](https://github.com/iotaledger/iota-core/assets/3079832/896ab2c7-2cd6-463b-8ecd-35896eaebd9f)

We already added:
```
    environment:
      - GOTRACEBACK=crash
      - GOMEMLIMIT=3000MiB
      - GOGC=100
```
to the docker-compose but it's still happening.

And the 2nd change was `--db.maxOpenDBs=2` which didn't solve the problem too.

Here is a profile (with PDFs :star_struck: ) of this node:

[pprof.validator-18_20240207-071251_all.zip](https://github.com/iotaledger/iota-core/files/14190279/pprof.validator-18_20240207-071251_all.zip)
