### ISSUE TITLE
Check uses of OnlineCommittee()

### ISSUE THREAD

**Issue by cyberphysic4l** [iotaledger/iota-core#641]
OnlineCommittee() from the SeatManager may have some issues in how it is used.

For example, it is used to initialize the seat count of the SpendDAG, but the total committee size for the epoch should be used for this, not just the active committee. https://github.com/iotaledger/iota-core/blob/3563539fa5f42857885888a15f056d7f37d6427a/pkg/protocol/engine/ledger/ledger/ledger.go#L67

**Comment by cyberphysic4l** [comment]
We could either set the online committee to be empty at the beginning of an epoch, or set it to the full committee as though each new committee member issues a block at the very beginning of the epoch. Initializing it as empty may result in very rapid acceptance at the beginning of the epoch, so it is probably more stable to choose the latter option and if some committee members are offline it will take a few slots (activity window = MinCA slots to be precise) for acceptance to resume.

**Comment by jonastheis** [comment]
> it is used to initialize the seat count of the SpendDAG, but the total committee size for the epoch should be used for this, not just the active committee. 

Currently, we only track acceptance within the `SpendDAG` and confirmation of transactions happens [if a transaction is accepted and any of its attachment blocks becomes confirmed](https://wiki.iota.org/learn/protocols/iota2.0/core-concepts/consensus/consensus-flags/#confirmation-of-conflicting-transactions). Therefore, using `OnlineCommittee` should be correct here. 

We should verify though if it is enough to pass the `Size` function of the `OnlineCommittee` (if it doesn't change). Or if we need to pass `OnlineCommittee` itself (or even the `SeatManager`) and call `Size` via the retrieved `OnlineCommittee`

**Comment by piotrm50** [comment]
Improved how online committee size is passed to SpendDAG and TipSelection in #674
