### ISSUE TITLE
Complete IOTA 2.0 whitepaper

### ISSUE THREAD

**Issue by vekkiokonio** [iotaledger/iota-core#667]

**Comment by vekkiokonio** [comment]
Gather documentation around IOTA 2.0 and include it in a single white paper document. Important to verify that information in it is up-to-date and matches the iota-core implementation.

**Comment by darcy-camargo** [comment]
- The first version/draft was finished.
- There are 3 figures to be updated. Marcos is working on them.
- Comms (David/Gunnar) are currently working on reviewing the contents of Part 1 and grammar of the whole document.
- Alex (Core Team) reviewed Part 2 and is currently reviewing Part 1.
- After their revisions is done, we will plan external revisions.
- External revision will be done by selected comunity members and partners. Comms will select the community members in the same way we did with the Educational Campaign. Research will decide on the partners to be included in the next call. 
- Work on this is on hold until the revisions are finished. We will discuss the time we will dedicate addressing the comments after this.

**Comment by darcy-camargo** [comment]
- Core team and comms finished their revision
- Research team to work on addressing comments.
- During next planning call to set a deadline.
- Next step is setting up community and partners revision.

**Comment by darcy-camargo** [comment]
Whitepaper was completed with all internal revision and its ready to be shared.

**Comment by elix1er** [comment]
happening?
