### ISSUE TITLE
Add a TxFailureReason for multiple input side ImplicitAccountCreationAddress?

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota-core#679]
In https://github.com/iotaledger/tips/blob/tip42/tips/TIP-0042/tip-0042.md#conversion-semantic-transaction-validation-rules, the TIP says `No other Implicit Account Creation Address is present on the input side of the transaction.`.
There is currently no specific TxFailureReason for this and `TxFailureSemanticValidationFailed` is used instead. Is this case worth adding a new error variant or are we fine keeping the generic one?
Asking so we can align in the SDK, thanks :)

**Comment by Thoralf-M** [comment]
I think it would be worth to reconsider the mapping of many errors.
For delegation errors for example there is only this one specific case `20 - denotes that fail to claim delegation reward.`, all other delegation errors just end up in `255 - denotes that the semantic validation failed.` which isn't very helpful.
Having a specific transactionFailureReason for every case may be too much, but at least mapping multiple errors to a delegation related transactionFailureReason would be an improvement already

**Comment by muXxer** [comment]
We should move the `iota-core/pkg/retainer/retainer/errors.go` to iota.go in the same step.
