### ISSUE TITLE
Fix the parameters for the docker network

### ISSUE THREAD

**Issue by muXxer** [iotaledger/iota-core#682]
We should change the current parameters, so that we can test if the mana calculation works correctly on client side.

Especially the workscore parameters and congestion control parameters should be changed.

**Comment by muXxer** [comment]
I set some values other than zero for now in https://github.com/iotaledger/iota.go/pull/667, as a first "quick fix".

**Comment by cyberphysic4l** [comment]
Mock node's mana calculations may need adjustment once the workscore params are set.
https://github.com/iotaledger/iota-core/blob/c773257169e63d886cfb308da15d975c08dfa516/pkg/testsuite/mock/utils.go#L40-L45
