### ISSUE TITLE
Finish up client validators API to handle pages

### ISSUE THREAD

**Issue by daria305** [iotaledger/iota-core#685]
Node sends the validators response in batches with cursor indicating pages. Client method should allow for requesting all pages

**Comment by muXxer** [comment]
Add a testcase as well please.

**Comment by daria305** [comment]
Found out a bug on the node side implementation, issue opened [#721](https://github.com/iotaledger/iota-core/issues/721)

**Comment by daria305** [comment]
Node side testing will be handled in issue: #722
