### ISSUE TITLE
Store block and transaction failure error message in retainer

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger/iota-core#697]
To improve our developer experience, we should allow a node to be configured, such that the full error message string of a block or transaction failure (perhaps transactions only is sufficient) is stored in the retainer and returned in the `/api/core/v3/blocks/{blockId}/metadata` and/or `/api/core/v3/transactions/{transactionId}/metadata` APIs.

That way, developers have much more information for debugging.

By default, the option should be disabled but all our test networks as well as the docker-network should have that option enabled.

## Example

Instead of just getting `TxFailureDelegationStartEpochInvalid`, the full error message also includes the context of which delegation output was problematic and what start epoch was expected:

```
failed to execute transaction: invalid chain transition; inner err: invalid delegation output transition: invalid start epoch (is 5, expected 1); Delegation 0x0000000000000000000000000000000000000000000000000000000000000000: new chain 0x8b0056a3897eb4e0e7b66641e566c800287bed155499d1c8052704b9332cf013 (*iotago.DelegationOutput) state transition failed
```

**Comment by muXxer** [comment]
Done in #769
