### ISSUE TITLE
Cleanup internal node events and hook correctly with API

### ISSUE THREAD

**Issue by muXxer** [iotaledger/iota-core#701]
The `inx-faucet` sometimes sends several payouts, because it adds the user requests back to the queue in case of an error.

```
docker-network-inx-faucet-1        | 2024-01-25T18:23:21Z	WARNING	Faucet	checkPendingTransactionState failed: failed to fetch metadata of the pending transaction, blockID: BlockID(0x3792a2572f63c9ddd330aed36303026ea062531d82dba7a512d24db010a0239374000000:116), txID: TransactionID(0xfa4955eeaa7824ef62849f8c61954743340deb3affe94c5ac43ef0dd80b886136a000000:106) 
```

It seems to me that the block is not known to the node, even though it accepted the block and returned "OK" via inx.
We should wait in the node before returning, until it is 100% certain that the block will be sent to the network.

- maybe we can return earlier in the post block endpoint in case of error
- we also need to make sure that the retainer saw the block/tx before we return from the post block endpoint in the other cases

**Comment by cyberphysic4l** [comment]
Could be as simple as changing the event here https://github.com/iotaledger/iota-core/blob/c91cb76e89b54eaf846c6e2c412663952e5ffc38/pkg/blockhandler/blockhandler.go#L115-L116
