### ISSUE TITLE
Add option to validate snapshot after download

### ISSUE THREAD

**Issue by alexsporn** [iotaledger/iota-core#708]
Validate the snapshot and compare the calculated merkle roots to the latest commitment.
This is related to #707

**Comment by jonastheis** [comment]
This is not directly related to validating a single snapshot but still worth considering so users can make sure they're downloading a "correct" snapshot: It would be great if we could compare the (claimed) hashes of different snapshot sources before downloading. And if they differ let the user decide which one should be downloaded. + verifying that the downloaded snapshot actually corresponds to the claimed hash.

**Comment by piotrm50** [comment]
@polinikita is implementing a feature in #707 to verify ledger state agains the latest commitment in the database. This will allow verifying that the ledgerstate loaded from the snapshot matches the latest commitment in the snapshot. There is still risk that the latest commitment is forged.
