### ISSUE TITLE
DAG-DLT workshop preparation

### ISSUE THREAD

**Issue by NaitsabesMue** [iotaledger/iota-core#710]
We are organizing a workshop on DAG-based DLTs at https://icbc2024.ieee-icbc.org/workshop/dag-dlt.

```[tasklist]
### Tasks
```

**Comment by vekkiokonio** [comment]
Contacted a number of potential interested authors and invited speakers.

**Comment by vekkiokonio** [comment]
- Finalized contacted list of potential interested researchers and previous participants.
- Invited keynote speaker.

No more tasks related to the workshop for now

**Comment by vekkiokonio** [comment]
- Finalized contacted list of potential interested researchers and previous participants.
- Invited keynote speaker.

No more tasks related to the workshop for now
