### ISSUE TITLE
Node reports healthy but it is not

### ISSUE THREAD

**Issue by shufps** [iotaledger/iota-core#806]
Network is at 102692 but `latestFinalizedSlot` is at 90115:
```json
{
  "name": "iota-core",
  "version": "1.0.0-alpha.8",
  "status": {
    "isHealthy": true,
    "acceptedTangleTime": "1709622328498843859",
    "relativeAcceptedTangleTime": "1709622329066738472",
    "confirmedTangleTime": "1709496705999999999",
    "relativeConfirmedTangleTime": "1709567311749196564",
    "latestCommitmentId": "0x1ad4e6230d8c0dbffefe067fa9f1a180c364569236ba6738bfa8eda89e6fc2721a910100",
    "latestFinalizedSlot": 90115,
    "latestAcceptedBlockSlot": 102685,
    "latestConfirmedBlockSlot": 90122,
    "pruningEpoch": 0
  },
```

but the node reports itself as healthy what imho it is not.

**Comment by alexsporn** [comment]
@shufps healthy means acceptance and the acceptedTangleTime goes on, this does not depend on finalization.

**Comment by shufps** [comment]
@alexsporn yes, I remember that you explained it to me already but it doesn't make much sense - at least not from devops perspective :sweat_smile: 

Let's assume I look at my monitoring and everything is green and the nodes are actually not "healthy" because they lag behind 10k slots with finalization, the health endpoint is useless then for monitoring.

What alternative would you suggest? Using the information from the info endpoint and compare numbers? :man_shrugging: 

Wouldn't it make more sense to have a health endpoint that actually says if everything in the node is fine?

And a side question - How can it happen that finalization is lagging so far behind?

**Comment by alexsporn** [comment]
> And a side question - How can it happen that finalization is lagging so far behind?

For that you need to look at the whole network. Maybe you got a network split. The next release will be more stable in this regard.

**Comment by muXxer** [comment]
Can this be closed? Or do we need an additional flag that says that finalization is delayed?

**Comment by muXxer** [comment]
We could add a `isFinalizationDelayed` flag based on the latest committed slot and the finalized slot. If that differs more than for example 2 slots, we could signal that the finalization is delayed.
