### ISSUE TITLE
iota-core node hangs during shutdown

### ISSUE THREAD

**Issue by shufps** [iotaledger/iota-core#823]
On the latest `alpha.9` we have the problem that nodes cannot be shutdown / restarted gracefully.

```
...
Received shutdown request - waiting (max 185 seconds) to finish processing (Close p2p peer database, P2P, Protocol) ... 
...
```

I attached a pprof profile, maybe it gives insights where it is hanging.
[pprof.access-5_20240308-132108_all.zip](https://github.com/iotaledger/iota-core/files/14538612/pprof.access-5_20240308-132108_all.zip)

**Comment by jkrvivian** [comment]
This error is not reproducible anymore.
