### ISSUE TITLE
Very high memory consumption after start

### ISSUE THREAD

**Issue by shufps** [iotaledger/iota-core#843]
I tried to restart nodes, there are some nodes that use excessive much memory directly after the restart:

![image](https://github.com/iotaledger/iota-core/assets/3079832/f5c1614d-ca48-4eb0-998e-e079ad80ae96)

Here is a memory profile:
[pprof.validator-0_20240315-172841_all.zip](https://github.com/iotaledger/iota-core/files/14618902/pprof.validator-0_20240315-172841_all.zip)

**Comment by shufps** [comment]
hmm it looks like as it is resyncing, maybe the shutdown was not graceful.

Mmmhmm, can it be that TRACE log level spams so hard during syncing that the server almost OOMs?

![image](https://github.com/iotaledger/iota-core/assets/3079832/797aa790-e5da-47ce-a0db-83db545c77c6)


According to the profile most memory is used by the Logger :confused:

**Comment by shufps** [comment]
I tried to rerun the resync with DEBUG log level but it still needs a lot of memory.

Profile for the 2nd run:
[pprof.validator-0_20240315-174545_all.zip](https://github.com/iotaledger/iota-core/files/14619051/pprof.validator-0_20240315-174545_all.zip)

**Comment by fhb191309** [comment]
I can confirm this. This occurred also in our tests while starting up our nodes

This is with 4 Cores and 8 GB RAM
<img width="1403" alt="CPU usage_4 cores_8 GB RAM" src="https://github.com/iotaledger/iota-core/assets/69419978/38ef9c7e-0207-4fff-8ee4-73535fbf218b">

This is with 2 Cores and 8 GB RAM
<img width="1412" alt="CPU usage_2 cores_8 GB RAM" src="https://github.com/iotaledger/iota-core/assets/69419978/d9c4e013-882c-4d3b-ad31-9d133bd4e65e">

**Comment by muXxer** [comment]
@fhb191309 do you also have a memory profile? I only see CPU and IOPS

**Comment by shufps** [comment]
@muXxer here is another profile from a node that was not syncing and consumes a lot of memory:
[pprof.access-2_20240320-091414_all.zip](https://github.com/iotaledger/iota-core/files/14664115/pprof.access-2_20240320-091414_all.zip)

![image](https://github.com/iotaledger/iota-core/assets/3079832/35f9fdae-a9e1-4f51-9001-e151a53580e8)

**Comment by HM4704** [comment]
I have a single node running and it seams to leak around 100 MB per day without any interactions.

**Comment by jonastheis** [comment]
@shufps what exactly is/was happening on the network? Block or transaction spam? was it still finalizing?

**Comment by shufps** [comment]
@jonastheis as far as I understand, when a node doesn't shutdown gracefully, it deletes the last unhealthy epoch and syncs new and the syncing takes a lot of memory until it dies on OOM

**Comment by jonastheis** [comment]
As discussed: this is expected as the commitments are created in memory when starting to sync a new chain. If the snapshot that the node is started from is old, there's simply too many commitments (~8k per day to be synced) and memory explodes. 

For now, to solve this we should either expose a snapshot API or a CLI tool to create a snapshot. Joining/syncing nodes should then always start from a very recent snapshot to avoid this problem. @muXxer @shufps

**Comment by muXxer** [comment]
Should be fixed with #903
