### ISSUE TITLE
Mana manager rollback not working correctly

### ISSUE THREAD

**Issue by cyberphysic4l** [iotaledger/iota-core#880]
Problem observed in the ressims network when chain switching. After rolling back, there is an error in the mana manager when calculating the quantum for a certain issuer, the BICUpdateTime (142) in the mana manager is already ahead of the scheduler update slot (141). This suggests that the mana manager state did not roll back correctly.
```docker-network-node-1-validator-1  | 2024-03-20T12:38:28Z       TRACE   Protocol.Engine1                        Scheduler.BlockDropped (block=BlockID(0xe61bf3bff6e7dac0e139576f4cd82e7065e2b38c72cff8f5540d865ee29cc1b98e000000:142) err=failed to calculate mana for account 0x6aee704f25558e8aa7630fed0121da53074188abc423b3c5810f80be4936eb6e in slot SlotIndex(141): BIC update time (142) or output creation slot (5) later than requested slot (141))```

**Comment by muXxer** [comment]
As stated in #848 :
```
We haven't seen that problem during testing for a while, so I assume it's been resolved by one of the other fixes
```
