### ISSUE TITLE
SIGSEGV short after starting

### ISSUE THREAD

**Issue by shufps** [iotaledger/iota-core#901]
I tried to resync one of our nodes from scratch (deleted `db/*`) and after a couple of seconds, it crashed with SIGSEGV.

Here is the log of the node:
[access-2_2024-04-02-06.log.zip](https://github.com/iotaledger/iota-core/files/14832884/access-2_2024-04-02-06.log.zip)

**Comment by shufps** [comment]
we seem to have this problem on multiple nodes :see_no_evil:

**Comment by shufps** [comment]
This still happens on `alpha.14`

**Comment by piotrm50** [comment]
Solved in #913
