### ISSUE TITLE
Optimize WarpSync process

### ISSUE THREAD

**Issue by piotrm50** [iotaledger/iota-core#902]
WarpSync process is performing some actions that it possibly doesn't need to. Ideas to be discussed.

1. Do not schedule blocks/gossip/add to tip pool when WarpSyncing
2. Do not cast SpendDAG votes when WarpSyncing
3. Don’t handle weight propagation when WarpSyncing
4. Indexer is slow while syncing - `Applying slot 12464 with 0 new and 0 consumed outputs took 1.242s` 
5. Increase number of workers (done in #897)

**Comment by jonastheis** [comment]
I think 2-5 we shouldn't do now as it might introduce complications down the line and 1 is already done in #896
