### ISSUE TITLE
Protocol Parameters for Testnet

### ISSUE THREAD

**Issue by shufps** [iotaledger/iota-core#904]
We currently use the protocol parameters from the "docker" profile of the genesis-snapshot generator.

I was told that these parameters are not suitable for a real network but I have no idea how they should look like.

For this reason, I'm opening this as issue so they can be discussed / determined.

**Comment by BingYang-Lin** [comment]
Last time @piotrm50 suggested to modify the Liveness parameters in `presets.go`
```
iotago.WithLivenessOptions(20, 30, 5, 10, 15),
```
And in alpha.14 it works well for 150 blk spamming rate.

**Comment by bingyanglin** [comment]
Last time @piotrm50 suggested to modify the Liveness parameters in presets.go

iotago.WithLivenessOptions(20, 30, 5, 10, 15),
And in alpha.14 it works well for 150 blk spamming rate.

**Comment by alexsporn** [comment]
https://github.com/iotaledger/iota-core/blob/develop/tools/genesis-snapshot/presets/presets_yaml.go
